---
title: "Analysis"
author: "Elena"
date: "2024-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries and data
```{r}
library(foreign)
library(tidyverse)
library(lme4)

data <- read.spss("Data/CEDS_Archived.sav", to.data.frame=TRUE)
```

Data wrangling

```{r}
#Select variables
data_selected<- data %>% select(ID, depdxma, Saliva1Time, Saliva2Time, Saliva3Time, Saliva4Time, Saliva5Time, Saliva6Time, Saliva7Time, Saliva1done, Saliva2done, Saliva3done, Saliva4done, Saliva5done, Saliva6done, Saliva7done) %>% mutate(ID = as.factor(ID))

#Create time and saliva variables

data_gathered<- data_selected %>% gather(Time, Saliva, Saliva1Time:Saliva7Time)%>%filter(Saliva1done == "yes" & Saliva2done == "yes" & Saliva3done == "yes" & Saliva4done == "yes" & Saliva5done == "yes" & Saliva6done == "yes" & Saliva7done == "yes")%>% select(ID, depdxma, Time, Saliva)%>% filter(depdxma=="1" | depdxma == "0") %>% mutate(Time = as.factor(Time)) #filter only those that completed all samples and then select only the relevant columns.
```

Summary statistics

```{r}
summary <-  data_gathered %>% group_by(Time, depdxma) %>%
  summarise(n=n(),
            mean=mean(Saliva, na.rm = T),
            sd=sd(Saliva, na.rm = T),
            se=sd/sqrt(n),
            lower=mean-se*1.96,
            upper=mean+se*1.96)
summary

ggplot(summary, aes(x = Time, y = mean, group = depdxma)) +
  geom_line(aes(lty = as.character(depdxma), color = depdxma),
            position = position_dodge(width = 0.1)) +
  geom_errorbar(aes(ymax = upper, ymin = lower), width = 0.1,
                position = position_dodge(width = 0.1)) +
  geom_point(aes(shape = as.character(depdxma)),
             position = position_dodge(width = 0.1)) +
  guides(lty = "none", shape = "none")+
  theme_classic()+
  labs(x="Sample Time",y="Saliva")
```

Linear mixed effects model

```{r}
#assign contrast codes

contrasts(data_gathered$Time) <- contr.poly(7) #polynomial contrast codes are chosen because the blocks are ordinal and equally

mod <- afex::mixed(Saliva ~ Time*depdxma + (1|ID), data=data_gathered, check_contrasts = FALSE, method="KR")
summary(mod)
mod #significant effect of time, non-significant interaction term

#Test assumptions of linear mixed effects models

tdat <- data.frame(predicted=predict(mod$full_model), residual = residuals(mod$full_model))

ggplot(tdat,aes(x=predicted,y=residual)) + geom_point() + geom_hline(yintercept=0, lty=3)

ggplot(tdat,aes(x=residual)) + geom_histogram(bins=40, color="black")

ggplot(tdat,aes(sample=residual)) + stat_qq() + stat_qq_line()

raneff <- lme4::ranef(mod$full_model)

hist(raneff$ID$`(Intercept)`, breaks=15) #random effect of participant normal
```
